### ISSUE TITLE
`inert` attribute

### ISSUE THREAD

**Issue by atomiks** [theKashey/aria-hidden#15]
The `inert` attribute ([example](https://twitter.com/diegohaz/status/1650282161092558850)) can be used on elements like `aria-hidden` is for virtual cursors, but for tabbing instead. This allows the user to escape into the address bar and console of a page and removes the need to use focus guards to trap focus. 

I think the DOM traversal in this library is identical and can be used for this attribute as well?

**Comment by atomiks** [comment]
I just saw this was added [last year](https://github.com/theKashey/aria-hidden/commit/d5b99993e07d402e22913dda86d6958bc3dc48ee) already 😆  - second time I made an issue and something is already supported. Sorry for the issue!

**Comment by theKashey** [comment]
You are welcome. I should advertise some features a little bit more.
