### ISSUE TITLE
Export `applyAttributeToOthers` function

### ISSUE THREAD

**Issue by atomiks** [theKashey/aria-hidden#16]
Hello again 😄  

I'd like to leverage the DOM walking logic of this lib, but without marking anything with `inert` or `aria-hidden` in certain cases. The particular case I'm interested in is a **non-modal** popover, which won't have `aria-hidden` or `inert` applied. 

Anything rendered **after** the popover opened should be considered a third-party extension to prevent "outside press" logic from running when clicking on them.

So I can do:

```js
const undo = others(node, '[data-my-identifier]');

// on outside press,
// if the popover doesn't contain the target AND it has
// our marker
if (e.target.closest('[data-my-identifier]')) {
  // then we know it's not a third-party popup/toast that got injected
  // after it opened
  closePopover();
  undo();
}
```

https://twitter.com/diegohaz/status/1671928841445556231

Is this something that makes sense?

https://github.com/theKashey/aria-hidden/blob/9220c8f4a4fd35f63bee5510a9f41a37264382d4/src/index.ts#L48

**Comment by theKashey** [comment]
I think that is possible, but will require a little internal refactoring to un-globalize "counters".
More importantly - move functionality to another library, as this one has a very specific "name" and exposing unrelated functionality is just a bad smell.
