### ISSUE TITLE
usage of console.error

### ISSUE THREAD

**Issue by herzaso** [theKashey/aria-hidden#17]
I'm using [floating-ui](https://floating-ui.com/) which uses your package and I also use [jest-fail-on-console](https://www.npmjs.com/package/jest-fail-on-console) which fails my jest tests if console is being used, but in a specific scenario, I get an error from [your package](https://github.com/theKashey/aria-hidden/blob/9220c8f4a4fd35f63bee5510a9f41a37264382d4/src/index.ts#L34).

What is this error? Can you remove the console use?

**Comment by theKashey** [comment]
This is actually an error. I am not sure how exactly it's used in floating-ui (probably [like this](https://github.com/floating-ui/floating-ui/blob/05a7fc975d69638da6ee1b7ff856535aa84a8267/packages/react/src/utils/markOthers.ts#L43C47-L43C71)) - but in short - one of the given nodes is not contained inside `body`, and that is an error.

As floating-ui duplicated aria-hidden there is nothing I can do, but I would not suppress this error in any case.
