### ISSUE TITLE
Crashes on IE11 to "Object doesn't support property or method 'contains''"

### ISSUE THREAD

**Issue by viheikki** [theKashey/aria-hidden#4]
On IE11 only HTMLElement has .contains -method. Aria-hidden will call .contains also on e.g. SVGElement, which will cause the titular error on IE11.

See https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

**Comment by viheikki** [comment]
Proposed fix:
https://github.com/theKashey/aria-hidden/pull/5

**Comment by viheikki** [comment]
Could you also publish a new version to npmjs with the IE11 fix, thank you.

**Comment by theKashey** [comment]
Published as 1.1.3
