### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by michaelbull** [theKashey/aria-hidden#8]
Hi. I am using your package in conjunction with [`license-webpack-plugin`](https://www.npmjs.com/package/license-webpack-plugin). This plugin automatically fetches licensing information from packages and bundles all licenses into a single file for end-users. It does this by searching for the LICENSE file in your shipped package.

I did try looking for licensing information in your repository and it seems like the only place it's reference is in `package.json`, however there is no actual LICENSE file in the repository detailing the terms of the LICENSE (i.e. author details, copyrighted year, etc).

Please can you consider adding a LICENSE file to both the repository, and including it in the `files` part of your `package.json` so that is included with the package on npm?

Thanks in advance.

**Comment by theKashey** [comment]
Absolutely all other projects under my maintenance have the same problem 😭
