### ISSUE TITLE
Ability to pass an array?

### ISSUE THREAD

**Issue by atomiks** [theKashey/aria-hidden#9]
There are scenarios (e.g. comboboxes) where you might want to hide everything but two elements: the input and listbox popup. This should allow you to portal the listbox to the end of the document but still allow touch-based screenreaders to function properly.

**Comment by atomiks** [comment]
I just checked the source code and an array is already allowed lol. I guess the docs could specify this. Thanks!

**Comment by theKashey** [comment]
Your are welcome :)
